import {StyleSheet} from 'react-native';
import {COLORS} from './theme';
import {sF, sH, sW} from './responsive';

export const globalStyles = StyleSheet.create({
  heading: {
    fontFamily: 'Inter',
    fontSize: sF(36),
    fontWeight: 500,
    lineHeight: sH(43.57),
    letterSpacing: -0.06 * sF(36),
    textAlign: 'left',
    color: COLORS.primaryGreen,
  },
  bodyText: {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: sF(16),
    lineHeight: sH(19.36),
    letterSpacing: sW(-1),
  },
  bodyTextSmall: {
    fontFamily: 'Inter',
    fontWeight: 400,
    fontSize: sF(12),
    lineHeight: sH(14.52),
    color: COLORS.mediumGreen,
  },
  buttonText: {
    fontFamily: 'DMMono',
    fontWeight: 400,
    fontSize: sF(14),
    lineHeight: sH(18.23),
  },
  labelButton: {
    fontFamily: 'DMMono',
    fontSize: sF(12),
    fontWeight: 400,
    lineHeight: sH(18.23),
    textAlign: 'left',
  },
  labelSmall: {
    fontFamily: 'DMMono',
    fontSize: sF(12),
    fontWeight: 500,
    color: COLORS.mediumGreen,
    lineHeight: sH(15.62),
    letterSpacing: sF(12) * 0.08,
    textAlign: 'left',
  },
  labelMedium: {
    fontFamily: 'DMMono',
    fontSize: sF(14),
    fontWeight: 500,
    lineHeight: sH(18.23),
    color: COLORS.mediumGreen,
  },
  button: {
    backgroundColor: COLORS.primaryGreen,
    height: sH(34),
    borderRadius: sW(100),
    paddingHorizontal: sW(16),
    paddingVertical: sH(8),
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: sW(1),
    textTransform: 'uppercase',
  },
  pressedButton: {
    backgroundColor: COLORS.darkGreen,
    height: sH(34),
    borderRadius: sW(100),
    paddingHorizontal: sW(16),
    paddingVertical: sH(8),
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  outlineButton: {
    height: sH(34),
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: COLORS.primaryGreen,
    borderRadius: sW(100),
    paddingHorizontal: sW(16),
    paddingVertical: sH(8),
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: sW(1),
  },
  outlinePressedButton: {
    borderWidth: 1,
    borderColor: COLORS.primaryGreen,
    backgroundColor: COLORS.greyshGreen,
    height: sH(34),
    borderRadius: sW(100),
    paddingHorizontal: sW(16),
    paddingVertical: sH(8),
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxRow: {
    gap: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkboxContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: sW(16),
    height: sH(16),
    borderRadius: sW(4),
    borderWidth: 1,
    borderColor: COLORS.greyshGreen,
  },
  checkboxActive: {
    backgroundColor: COLORS.darkGreen,
    width: sW(16),
    height: sH(16),
    borderRadius: sW(4),
    borderWidth: 1,
    borderColor: COLORS.darkGreen,
  },
  checkboxIcon: {
    fontWeight: 700,
  },
  error: {
    padding: sW(16),
    color: 'red',
    backgroundColor: '#ff000010',
    borderRadius: sW(24),
  },
});
